### ISSUE TITLE
the access token expires, please re-run [zoomeye init] command.it is recommended to use API KEY for initialization!

### ISSUE THREAD

**Issue by Q1984** [knownsec/zoomeye-python#118]
Hi!

Looks like the search is broken somewhere.

```
zoomeye init -apikey "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
Role: Free
Quota: 2895
successfully initialized


zoomeye search "telnet" -num 1
the access token expires, please re-run [zoomeye init] command.it is recommended to use API KEY for initialization!


zoomeye -v

         ,----,                                                                 
       .'   .`|                            ____      ,---,.                     
    .'   .'   ;                          ,'  , `.  ,'  .' |                     
  ,---, '    .' ,---.     ,---.       ,-+-,.' _ |,---.'   |                     
  |   :     ./ '   ,'\   '   ,'\   ,-+-. ;   , |||   |   .'                     
  ;   | .'  / /   /   | /   /   | ,--.'|'   |  ||:   :  |-,      .--,   ,---.    {v2.2.0 }
  `---' /  ; .   ; ,. :.   ; ,. :|   |  ,', |  |,:   |  ;/|    /_ ./|  /     \  
    /  ;  /  '   | |: :'   | |: :|   | /  | |--' |   :   .' , ' , ' : /    /  | 
   ;  /  /--,'   | .; :'   | .; :|   : |  | ,    |   |  |-,/___/ \: |.    ' / | 
  /  /  / .`||   :    ||   :    ||   : |  |/     '   :  ;/| .  \  ' |'   ;   /|  
./__;       : \   \  /  \   \  / |   | |`-'      |   |    \  \  ;   :'   |  / | 
|   :     .'   `----'    `----'  |   ;/          |   :   .'   \  \  ;|   :    |  
;   |  .'                        '---'           |   | ,'      :  \  \   \  /   https://www.zoomeye.org/doc 
`---'                                            `----'         \  ' ; `----'   
                                                                 `--`           
```

OS: Kali

**Comment by lolminerxmrig** [comment]
me too.

**Comment by wh0am1i** [comment]
OK，let's me check

**Comment by kazundo** [comment]
api don't work with the version 3.0.0 !!!

**Comment by kazundo** [comment]
zoomeye init -apikey xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Traceback (most recent call last):
  File "/home/goda/.local/bin/zoomeye", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/goda/.local/share/pipx/venvs/zoomeye/lib/python3.13/site-packages/zoomeye/cli.py", line 133, in main
    args.func(args)
    ~~~~~~~~~^^^^^^
  File "/home/goda/.local/share/pipx/venvs/zoomeye/lib/python3.13/site-packages/zoomeye/core.py", line 61, in init
    init_key(api_key)
    ~~~~~~~~^^^^^^^^^
  File "/home/goda/.local/share/pipx/venvs/zoomeye/lib/python3.13/site-packages/zoomeye/core.py", line 37, in init_key
    user_data = zoom.userinfo()
  File "/home/goda/.local/share/pipx/venvs/zoomeye/lib/python3.13/site-packages/zoomeye/sdk.py", line 114, in userinfo
    resp = self._request(self.userinfo_api,
                         method='POST',
                         params={},
                         headers=headers)
  File "/home/goda/.local/share/pipx/venvs/zoomeye/lib/python3.13/site-packages/zoomeye/sdk.py", line 90, in _request
    raise ValueError(resp.json().get('message'))
ValueError: this service not aviliable in your area, please use api.zoomeye.ai instead
