### ISSUE TITLE
Python SDK error

### ISSUE THREAD

**Issue by rudy500** [knownsec/zoomeye-python#120]
Hi,

I working with python 3.9 and latest version of zoomeye, create this code invoke dork_search function and send error, attach code used:

```
import zoomeye.sdk as zoomeye
import time
zm = zoomeye.ZoomEye(api_key="XXXXXXXX-YYYY-ZZZZZ-PPPP-OOOOOOOOOOO")

data = zm.dork_search("app: apache, country:cn")
time.sleep(3)
zoomeye.show_site_ip(data)

``` 

error: 

Traceback (most recent call last):
  File "C:\USACH\Python Ciberseguridad\Códigos\Codigo Clase 5\ZoomeyeSearch.py", line 5, in <module>
    data = zm.dork_search("app: apache, country:chile")
  File "C:\Users\Rudy Pinochet\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\zoomeye\sdk.py", line 170, in dork_search
    resp = self._request(search_api, params=params, headers=headers)
  File "C:\Users\Rudy Pinochet\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\zoomeye\sdk.py", line 131, in _request
    raise ValueError(resp.json().get('message'))
ValueError: request invalid, validate usage and try again

Many thanks for you assistant

**Comment by jiugua9** [comment]
The sentence after polishing: "You can insert the code "print(resp.json())" with a print statement before line 131 in zoomeye\sdk.py, 
and the resulting output may be 
{'code': 'credits_insufficent', 'error': 'resource credits is insufficent', 'message': 'request invalid, validate usage and try again', 'url':  'https://www.zoomeye.org/api'}. 
This will help you identify the problem."
