### ISSUE TITLE
add python3 support

### ISSUE THREAD

**Issue by nixawk** [knownsec/ZoomEye-python#3]
```
root@sh:/tmp/SDK# python3
Python 3.5.2+ (default, Sep 22 2016, 12:18:14)
[GCC 6.2.0 20160914] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zoomeye
>>> zoomeye.zoomeye_api_test()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/SDK/zoomeye.py", line 120, in zoomeye_api_test
    zoomeye.username = raw_input('ZoomEye Username: ')
NameError: name 'raw_input' is not defined
```

**Comment by nixawk** [comment]
```
import sys


raw_input = raw_input if sys.version_info.major <= 2 else input

```

commit - https://github.com/ZoomEye/SDK/commit/7456027715cbe31228a12bbba5a472fa99ba4e90
