### ISSUE TITLE
-filter banner failed

### ISSUE THREAD

**Issue by kaichenkai** [knownsec/ZoomEye-python#38]
zoomeye search "telnet" -num 1 -filter banner
执行命令报错：
Traceback (most recent call last):
  File "/Users/kai/Desktop/kunion3/venv/bin/zoomeye", line 8, in <module>
    sys.exit(main())
  File "/Users/kai/Desktop/kunion3/venv/lib/python3.6/site-packages/zoomeye/cli.py", line 222, in main
    args.func(args)
  File "/Users/kai/Desktop/kunion3/venv/lib/python3.6/site-packages/zoomeye/core.py", line 111, in search
    cli_zoom.filter_data(filters, save)
  File "/Users/kai/Desktop/kunion3/venv/lib/python3.6/site-packages/zoomeye/data.py", line 474, in filter_data
    show.print_filter(equal, result[:self.num], has_equal)
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by Rosschach** [comment]
已修复
