### ISSUE TITLE
参考readme运行cli.py文件报错

### ISSUE THREAD

**Issue by zongdeiqianxing** [knownsec/zoomeye-python#66]
```
#python3 cli.py domain baidu.com 0
name                                                   timestamp      ip                       
Traceback (most recent call last):
  File "cli.py", line 235, in <module>
    main()
  File "cli.py", line 229, in main
    args.func(args)
  File "/root/tools/ZoomEye-python-master/zoomeye/core.py", line 228, in associated_domain_query
    DomainSearch(q, resource, page).show_information()
  File "/root/tools/ZoomEye-python-master/zoomeye/data.py", line 762, in show_information
    show.show_domain_info(info_data, total, self.page)
  File "/root/tools/ZoomEye-python-master/zoomeye/show.py", line 444, in show_domain_info
    printf("{:<55}{:<15}{:<25}".format(name, timestamp, ip))
TypeError: unsupported format string passed to list.__format__
```

**Comment by zongdeiqianxing** [comment]
show.py 444行可改为`printf("{:<55}{:<15}{:<25}".format(name, timestamp, ','.join(ip)))`
