### ISSUE TITLE
Got JSONDecodeError with dork_search

### ISSUE THREAD

**Issue by Zhanglin2017** [knownsec/zoomeye-python#85]
This happened a few times in last week. Not a big problem, but it would be nice if it fail-safe.

Traceback (most recent call last):
  File "C:\Users\zhang\eclipse-workspace\zoomeye\get_data.py", line 125, in <module>
    test()
  File "C:\Users\zhang\eclipse-workspace\zoomeye\get_data.py", line 15, in test
    data = zm.dork_search('+port:2404', facets=['country', 'city'])
  File "C:\Users\zhang\AppData\Roaming\Python\Python39\site-packages\zoomeye\sdk.py", line 188, in dork_search
    resp = self._request(search_api, params=params, headers=headers)
  File "C:\Users\zhang\AppData\Roaming\Python\Python39\site-packages\zoomeye\sdk.py", line 135, in _request
    raise ValueError(resp.json().get('message'))
  File "C:\Users\zhang\AppData\Roaming\Python\Python39\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\zhang\AppData\Roaming\Python\Python39\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "C:\Users\zhang\AppData\Roaming\Python\Python39\site-packages\simplejson\decoder.py", line 372, in decode
    obj, end = self.raw_decode(s)
  File "C:\Users\zhang\AppData\Roaming\Python\Python39\site-packages\simplejson\decoder.py", line 402, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Zhanglin2017** [comment]
Traceback (most recent call last):
  File "C:\Users\zhang\eclipse-workspace\zoomeye\get_data.py", line 125, in <module>
    test()
  File "C:\Users\zhang\eclipse-workspace\zoomeye\get_data.py", line 15, in test
    data = zm.dork_search("+port:5007", facets='country', page = 1)
  File "C:\Users\zhang\AppData\Roaming\Python\Python39\site-packages\zoomeye\sdk.py", line 188, in dork_search
    resp = self._request(search_api, params=params, headers=headers)
  File "C:\Users\zhang\AppData\Roaming\Python\Python39\site-packages\zoomeye\sdk.py", line 135, in _request
    raise ValueError(resp.json().get('message'))
  File "C:\Users\zhang\AppData\Roaming\Python\Python39\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\zhang\AppData\Roaming\Python\Python39\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "C:\Users\zhang\AppData\Roaming\Python\Python39\site-packages\simplejson\decoder.py", line 372, in decode
    obj, end = self.raw_decode(s)
  File "C:\Users\zhang\AppData\Roaming\Python\Python39\site-packages\simplejson\decoder.py", line 402, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by junyu1** [comment]
您好，我也遇到这个问题，请问您是怎么解决的？
